version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    command: gunicorn dualedu.wsgi:application --bind 0.0.0.0:8000
