# Generated by Django 5.2.3 on 2025-06-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='text_content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='material',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='material',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='main/material/audios/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='assignment_audio',
            field=models.FileField(blank=True, null=True, upload_to='main/material/audio/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='assignment_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/material/images/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subcategory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
