# Generated by Django 5.2.3 on 2025-06-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_text_content_material_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='material',
            name='text',
            field=models.TextField(default='Hozircha matn mavjud emas.'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
