# Generated by Django 5.2.3 on 2025-06-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_material_subcategory_material_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('youtube_url', models.URLField()),
            ],
        ),
    ]
